// Copyright 2011 The Closure Library Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This file has been auto-generated by GenJsDeps, please do not edit.

goog.addDependency('gsv/mvc.js', ['goog.gsv.mvc'], []);
goog.addDependency('gsv/model.js', ['goog.gsv.model'], []);
goog.addDependency('gsv/view.js', ['goog.gsv.view'], []);
goog.addDependency('gsv/zoomView.js', ['goog.gsv.view.ZoomView'], []);
goog.addDependency('gsv/service.js', ['goog.gsv.service'], []);
goog.addDependency('gsv/util.js', ['goog.gsv.util'], []);
goog.addDependency('../jquery/jquery-1.6.2.min.js', ['jquery'], []);
goog.addDependency('../jquery/jquery.tmpl.min.js', ['jquery.tmpl'], []);
goog.addDependency('../jquery/jquery-ui-1.8.16.custom.min.js', ['jquery.ui'], []);
goog.addDependency('../jquery/jquery.event.drag-2.0.min.js', ['jquery.event.drag'], []);
goog.addDependency('../jquery/dragscrollable.js', ['jquery.dragscroll'], []);
goog.addDependency('../raphael.js', ['raphael'], []);
